name: Terraform Build

on:
  push:
    branches: 
      - main

jobs:
  Terraform:
    name: Build Stage
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
      ENVNAME: 'test'
      ACCNAME: 'poc-lbaiao'
      TF_VERSION: 0.14.3
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKDIR: './'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{env.TF_VERSION}}
      
    - name: PLanning
      id: plan
      working-directory: ${{env.WORKDIR}}
      run: |
        make plan 'ACCNAME=${{env.ACCNAME}}' 'ENVNAME=${{env.ENVNAME}}' 'REGION=${{env.AWS_REGION}}'
        find . -name tfplan
    - name: Building
      id: apply
      working-directory: ${{env.WORKDIR}}
      run: |
        make apply 'ACCNAME=${{env.ACCNAME}}' 'ENVNAME=${{env.ENVNAME}}' 'REGION=${{env.AWS_REGION}}'
