name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Terraform:
    name: Build Stage
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-1'
      ENVNAME: 'test'
      ACCNAME: 'poc-lbaiao'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WORKDIR: './terraform-iac'

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.3
      
    - name: Make plan
      id: plan
      working-directory: ${{env.WORKDIR}}
      run: make plan 'ACCNAME=${{env.ACCNAME}}' 'ENVNAME=${{env.ENVNAME}}' 'REGION=${{env.AWS_REGION}}'

    - name: Make apply
      id: deploy
      working-directory: ${{env.WORKDIR}}
      if: github.ref =='refs/head/main' && github.event.name == 'push'
      run: |
        make apply 'ACCNAME=${{env.ACCNAME}}' 'ENVNAME=${{env.ENVNAME}}' 'REGION=${{env.AWS_REGION}}'
